### PR TITLE
Fix `?->` with succeeding PHP keyword

### LINKED ISSUE #1003: Null-safe operator followed by a property named `class` results in a syntax error
## Context
- php-parser 3.1.0
- https://github.com/shufo/vscode-blade-formatter/issues/544
  - I noticed this issue when my extension user reports the syntax check issue
 
## Problem

When property named `class` is exists after null safe operator, it will throws an exception.

```js
const target = `
  $record->learner->currentEnrollment?->class->grade->code
`;
// Retrieve the AST from the specified source
const eval = parser.parseEval(target);


// then it will throws an exception
/home/shuhei/develop/php-parser/src/parser.js:357
    throw err;
    ^

SyntaxError: Parse Error : syntax error, unexpected 'class' (T_CLASS) on line 2
    at Parser.raiseError (/home/shuhei/develop/php-parser/src/parser.js:349:17)
    at Parser.error (/home/shuhei/develop/php-parser/src/parser.js:397:15)
    at Parser.read_what (/home/shuhei/develop/php-parser/src/parser/variable.js:161:14)
    at Parser.recursive_variable_chain_scan (/home/shuhei/develop/php-parser/src/parser/variable.js:235:38)
    at Parser.read_variable (/home/shuhei/develop/php-parser/src/parser/variable.js:85:17)
    at Parser.read_expr_item (/home/shuhei/develop/php-parser/src/parser/expr.js:455:19)
    at Parser.read_expr (/home/shuhei/develop/php-parser/src/parser/expr.js:18:19)
    at Parser.read_statement (/home/shuhei/develop/php-parser/src/parser/statement.js:416:27)
    at Parser.read_top_statement (/home/shuhei/develop/php-parser/src/parser/statement.js:77:21)
    at Parser.read_start (/home/shuhei/develop/php-parser/src/parser/main.js:18:19) {
  lineNumber: 2,
  fileName: 'eval',
  columnNumber: 40
}
```

Maybe it is recognized as reserved word.

It only happens when you put `class` property after null safe operator.
So `class` property with normal property access is ok.

```php
// This works
$record->learner->currentEnrollment->class->grade?->code;
```

When I check syntax on php directly, it's ok. 

```php
$  php -v
PHP 8.1.2 (cli) (built: Aug 15 2022 12:24:10) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies

$ vim test.php
```

```php
<?php
echo $record->learner->currentEnrollment?->class->grade->code;
```

```bash
$  php --syntax-check test.php
No syntax errors detected in test.php
```

Sorry for no PR, I tried fix this but I don't know the right solution.

### PR DESCRIPTION
**Pull request by Sxxov**
Fixes #1003

I'm going to be honest, I have no idea what I'm doing, but all the tests seem to pass. Feel free to point me in the correct direction if this is absolutely not how you're supposed to do this.

### CODE REVIEW

**Comment by czosel** [comment]
Hi @Sxxov, thanks for contributing! Since I'm not the original author of the library I also always have to take some time to figure out PR reviews. Before I do that, could you add a test case that shows that your change fixes the issue you linked?

**Comment by Sxxov** [comment]
Ahh sorry for the long wait. I've added a test (::

**Review by cseufert — APPROVED** [review]
This looks good, LGTM

**Review by czosel — APPROVED** [review]
👍 thanks for contributing!

**Pull request merged**
