### PR TITLE
fix: don't skip blank lines in flexible nowdoc

### LINKED ISSUE #508: Can't parse multiple flexible nowdoc blocks with different indentation
Input:
```php
<?php
$a = <<<'EOT'
    a

    EOT;

$b = <<<'EOT'
  b
  EOT;
```
Output: `SyntaxError: Invalid body indentation level (expecting an indentation at least 2) on line 5`

### PR DESCRIPTION
**Pull request by czosel**
Fixes #508

### CODE REVIEW

**Comment by czosel** [comment]
Just noticed #506, which might make this change obsolete.

**Comment by ichiriac** [comment]
Hi @czosel, not sure it's fixed as the code you try to fix is still the same (https://github.com/glayzzle/php-parser/blob/master/src/lexer/strings.js#L243) - can you try again your tests over the master - I've merged the PR

**Comment by czosel** [comment]
Alright, I'll try to take a look later today! Thanks for looking into this :slightly_smiling_face:

**Comment by czosel** [comment]
I just updated the prettier plugin to `v3.0.0` of the parser, all the tests are passing! :tada: Thank you for the awesome work on this, and congratulations to the major release :100:

**Pull request closed without merging**
