### PR TITLE
Tests migration

### PR DESCRIPTION
**Pull request by b4dnewz**
* Migrated comment tests.
* Migrated expr tests.

Added jest env to eslint config to solve "expect is undefined"

### CODE REVIEW

**Comment by b4dnewz** [comment]
hi @ichiriac if you want to keep this PR open I will add more commits to it so we know who is migrating what and we don't work on the same files, is it good?

**Comment by ichiriac** [comment]
thanks @b4dnewz, it's good to me, I've done with the migration, if I get more time I'll focus on issues in order to finishe the 3.0 release.

**Comment by b4dnewz** [comment]
awesome, so I'll keep going until I've migrated all the tests

**Comment by ichiriac** [comment]
hi @b4dnewz, thanks for your work !

Do you think I can plan to merge or do you want to keep updating this PR ?

**Comment by b4dnewz** [comment]
Hi Ioan, unfortunately I haven't enough time the last month to continue on this, I'll try this weekend to migrate all the tests that I haven't done yet so it's ready to be merged, as it is now is half and half, is not so clear

**Comment by ichiriac** [comment]
Thanks dude, take your time, no hurry

**Comment by b4dnewz** [comment]
Ok @ichiriac, I've finally moved everything to jest but there are still some checks to do on the generated snapshot of 92ba262, because my knowledge of the php ast is limited I can't ensure the output is the one that is expected since some of the tests were missing on the original file.

Also there are some `// @todo` empty tests on 45dc0a3 that can probably can be filled using jest snapshot now, but I don't know exactly the php code to test.

The coverage now is  94.41% I don't why is decreased from 95% :(

**Comment by b4dnewz** [comment]
Also as a side note I would like to propose to upgrade from **grunt** to **webpack** and grunt-documentation to [esdoc](https://esdoc.org/) or something, since is deprecated

**Comment by ichiriac** [comment]
Hi @b4dnewz, you have done an amazing work ! 94% it's great and with jest it will be way more easy to improve it :+1:

I will merge it this weekend.

I'm also agree with you about gulp instead of grunt. Could you please help me on this with another PR, the main functionality is documentation, I need them as markdown in order to be directly published on github.

**Comment by b4dnewz** [comment]
@ichiriac if you want, esdoc can create an html documentation that can be published as subtree in gh-pages branch into a interactive documentation, or you need markdown for the github wiki?

besides that, yes I can provide to the webpack migration in a separate pr, I start working on it this weekend

**Comment by ichiriac** [comment]
I prefer markdown in order to publish them on docs folder directly on the repository, it's more easy to read them from github or on local instance.

If you want you could also try to bootstrap a gh-pages branch and I could link the glayzzle domain on github, but in that case we also need to integrate a playground in order to test AST over the latest release - but it could be great as I don't find time to update actual website.

Any idea is welcome so fell free to try whatever you want.

**Pull request merged**
