### PR TITLE
fix(precedence): right-associative operators

### LINKED ISSUE #548: Precedence of exponentiation operator
Hi @ichiriac 

In the PHP plugin for prettier an issue with the precedence of the exponentiation operator (`**`) was reported (https://github.com/prettier/plugin-php/issues/1421):

Input:
```php
1 + 2 ** 3;
1 ** 2 + 3;
```

The first expression is parsed incorrectly as `(1+2)**3`, the second correctly as `(1**2)+3` ([see playground](https://loilo.github.io/prettier-php-playground/#N4IgDgTgpgLjCWUIHkwIPYDsDOIBcok8mMA6vACYwAW+AHAAwA0IMAhgEblW14AsLAK7YoAFU648AMzYAbES2zEA5rKgBFQehhR8M+VBZhqYAGpIlWfCACsAOj4gWMCG3iyVAYXQBbH2wAFAAkA-BdBQxAOVwBjKABlGABPNWswbAgAWgAmJxBoAEdBeGgA12V-PTkFEGIRCBgytgq2KoMAXxYoCngYdBQ0eCxJUDZsGDCICM7azDBBCbwQAB4AfmMwAB1MbYBGAAIAan3s-YAqM-2AZgBuPfPL0+Pb7ZB2oA))

Screenshot from 2020-05-10 13-07-02

### PR DESCRIPTION
**Pull request by czosel**
This fixes a regression introduced in #485 

Fixes #548

### CODE REVIEW

**Comment by czosel** [comment]
Hi @ichiriac,
thanks for the review! `isRightAssociative` is only called from the one if branch that was changed. I also thought about changing the implementation of `isRightAssociative` first, but the function only does one thing: It takes an operator, and returns true if the operator is right-associtive. In order to tell if the "swap" should be performed in `resolvePrecedence`, the right-associativity should only be considered if the two operators have the same precedence level. This is equivalent to the two operators being different, because `**` and `??`, the only two right-associative operators PHP knows, have different precedence.

The bug only affected `**` and `??`, I added a test for the latter.

**Comment by czosel** [comment]
@ichiriac friendly ping 🙃

**Comment by ichiriac** [comment]
sorry, totally forgot this issue :smiley:

**Comment by ichiriac** [comment]
The PR is merged, I'll try to fix #511 and release a patch, this week or next one

**Comment by czosel** [comment]
No worries, thanks for merging! :tada:

**Pull request merged**
