### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by czosel**

### CODE REVIEW

**Comment by czosel** [comment]
CI is currently failing with errors like this:
```
Error: node_modules/@types/eslint-scope/index.d.ts(50,5): error TS2416: Property 'writeExpr' in type 'Reference' is not assignable to the same property in base type 'Reference'.
```
I have no typescript experience - any pointers are appreciated!

**Comment by cseufert** [comment]
I am pretty sure we do not want `@types/eslint-scope` to be installed, as it seems to be out of date, and eslint seems to have the types included already

**Comment by cseufert** [comment]
ok on further investigation, it appears that webpack imports @types/eslint-scope however the actualy eslint package looks to have updated typescript types. I am not sure how to solve this, without a PR to webpack to update its use of the eslint-scope types to consume directly from eslint.

**Comment by cseufert** [comment]
Well rolling back webpack to 5.96.0 to avoid this fix: https://github.com/webpack/webpack/issues/18916

has resulted in 
```
Error: node_modules/@types/node/module.d.ts(108,13): error TS2386: Overload signatures must all be optional or required.

```

which make no sense either.

**Comment by czosel** [comment]
@cseufert Thanks for looking into this! I tried following up on the remaining error, and it seems that installing `@types/node` fixes the issue: https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/70562#discussioncomment-10666769

**Comment by czosel** [comment]
@cseufert CI seems to pass now. Let me know if this is ready to be merged from your side :-)

**Review by cseufert — APPROVED** [review]
LGTM

**Pull request merged**
