### PR TITLE
add php8 nullsafe operator

### PR DESCRIPTION
**Pull request by Selion05**
#658 - Work in progress. Any feedback?

### CODE REVIEW

**Comment by czosel** [comment]
Looks good! Can you add a test?

I created a new branch called `php8` - I'd say we merge this into that branch first, such that @ichiriac can still take a look at the changes before it's merged into master.

**Comment by Selion05** [comment]
A separate branch sounds good. 

I added tests, basically I replicated most of the `propertylookup` tests. I just had a quick glance on the snapshots so they need some review!

**Comment by czosel** [comment]
I also didn't check all the snapshots, but what I saw looks good to me. Can you rebase on the current master? Then the CI should work as well, and we can start merging into the `php8` branch :+1:

**Review by czosel — APPROVED** [review]
👍

**Comment by czosel** [comment]
It would probably be a good idea to open a PR at the prettier php plugin that’s based on the php8 branch - sometimes we still notice some quirks when using the new features 🙃

**Pull request merged**
