### PR TITLE
feat: support for readonly class

### PR DESCRIPTION
**Pull request by genintho**
Is this approach ok?

According to https://php.watch/versions/8.2/readonly-classes

> Abstract classes final classes can also be declared readonly. The order of the keywords does not make a difference.

I know some tests will fail, I am showing this to verify that my approach is ok.

### CODE REVIEW

**Comment by czosel** [comment]
Hi @genintho - the general approach looks good to me! :+1:

**Comment by genintho** [comment]
Not sure why CI is breaking now. Running the typescript command locally show no difference. 🤔 I must be missing something.

**Comment by genintho** [comment]
@czosel this is ready for review.

I had to install `@types/node` to fix CI. In the CI, we globally install the most recent version of typescript, which conflict with the version implicitly installed in the repo.

I would love an alternative solution, but I already waste a couple of hours on this.

**Comment by czosel** [comment]
@genintho it seems the typescript issue was due to outdated transitive dependencies (see [here](https://github.com/microsoft/TypeScript/issues/51567) for details) - I just fixed it in #1050 by regenerating the lock file. Can you revert the changes to package.json and yarn.lock and rebase on `main`?

**Comment by genintho** [comment]
@czosel happy new year! 😄 

I did what you asked. We should be good to go.

**Comment by czosel** [comment]
@genintho thank you, all the best for you as well! :tada: 

LGTM :+1:

**Comment by czosel** [comment]
Released in `v3.1.3` :tada:

**Pull request merged**
