### PR TITLE
fix: add support for string concatenation in attributes

### PR DESCRIPTION
**Pull request by NorthBlue333**
Fixes https://github.com/glayzzle/php-parser/issues/1076

### CODE REVIEW

**Review by MaartenStaa — COMMENTED** [review]
LGTM! I think you need to commit the updated test snapshot though.

**Comment by NorthBlue333** [comment]
Indeed, my bad

**Review by czosel — APPROVED** [review]
LGTM

**Comment by czosel** [comment]
released as `v3.1.4` :tada: thanks for contributing @NorthBlue333 :100:

**Pull request merged**
