### PR TITLE
feat(php8): promoted properties

### PR DESCRIPTION
**Pull request by cseufert**
Basic impementation of promoted properties.

Added new AST node `promotedparameter` which is based on `parameter` with added `promote` property which can be `public`, `private`, or `protected`.

Is this the correct way to do this?

### CODE REVIEW

**Comment by cseufert** [comment]
This should close #655

**Comment by cseufert** [comment]
@czosel I think this approach should be changed in favour of how https://github.com/nikic/PHP-Parser/ handles it, and add a Param.flags that holds a int flag for visibility (public/private/protected) rather than a new ast node type. Ill add another PR for that when I get a chance

**Comment by czosel** [comment]
For reference: PHP-Parser parses
```php
class __proto__ {
  public function constructor(public int $id, private $name, protected ServerRequestInterface $req) {}
}
```
as
```
array(                                                                                                                                                                                                                                                 
    0: Stmt_Class(                                                                                                                                                                                                                                     
        attrGroups: array(                                                                                                                                                                                                                             
        )                                                                                                                                                                                                                                              
        flags: 0                                                                                                                                                                                                                                       
        name: Identifier(                                                                                                                                                                                                                              
            name: __proto__                                                                                                                                                                                                                            
        )                                                                                                                                                                                                                                              
        extends: null                                                                                                                                                                                                                                  
        implements: array(                                                                                                                                                                                                                             
        )                                                                                                                                                                                                                                              
        stmts: array(                                                                                                                                                                                                                                  
            0: Stmt_ClassMethod(
                attrGroups: array(
                )
                flags: MODIFIER_PUBLIC (1)
                byRef: false
                name: Identifier(
                    name: constructor
                )
                params: array(
                    0: Param(
                        attrGroups: array(
                        )
                        flags: MODIFIER_PUBLIC (1)
                        type: Identifier(
                            name: int
                        )
                        byRef: false
                        variadic: false
                        var: Expr_Variable(
                            name: id
                        )
                        default: null
                    )
                    1: Param(
                        attrGroups: array(
                        )
                        flags: MODIFIER_PRIVATE (4)
                        type: null
                        byRef: false
                        variadic: false
                        var: Expr_Variable(
                            name: name
                        )
                        default: null
                    )
                    2: Param(
                        attrGroups: array(
                        )
                        flags: MODIFIER_PROTECTED (2)
                        type: Name(
                            parts: array(
                                0: ServerRequestInterface
                            )
                        )
                        byRef: false
                        variadic: false
                        var: Expr_Variable(
                            name: req
                        )
                        default: null
                    )
                )
                returnType: null
                stmts: array(
                )
            )
        )
```

I agree, a visibility flag is the best way to represent this :+1:

**Comment by cseufert** [comment]
Use the implmentaton in #697

**Pull request closed without merging**
