### PR TITLE
refactor: byRef

### PR DESCRIPTION
**Pull request by evilebottnawi**
/cc @ichiriac here just fix

in the next PR i want to remove `byRef` node and revert some changes from https://github.com/glayzzle/php-parser/commit/fbfd46f7401c468ef38eac9e50b5ac8ed35cde9c

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@ichiriac hm, why? `AssignRef` === `Assign` with `ref`, we can reduce unnecessary nodes, php parser has many unnecessary nodes

**Comment by ichiriac** [comment]
`AssignRef` !== `Assign` - because `AssignRef` works only on `=` operators, so it's a subset of assign (without the need of operator property), also `AssignRef` does not have the same precedence as `Assign` with operator `=`

**Comment by evilebottnawi** [comment]
@ichiriac after `byRef` node, a lot of code very dirty, it is hard to do in one PR, maybe we can merge this as is and i will do this in other PR, also i can't find information about `precedence` https://www.php.net/manual/en/language.operators.precedence.php

**Comment by evilebottnawi** [comment]
ok, WIP

**Comment by evilebottnawi** [comment]
@ichiriac done :+1:

**Comment by ichiriac** [comment]
thanks @evilebottnawi - it's great

**Comment by evilebottnawi** [comment]
@ichiriac WIP on remove unnecessary stuff for `byRef` node

**Comment by ichiriac** [comment]
in principle I don't use byRef node anymore, see https://github.com/glayzzle/php-parser/commit/72cde999df66069aee8ca3f58b4147f7df4090cc - but still it may be cases where the byref syntax is too permissive

**Comment by evilebottnawi** [comment]
@ichiriac i will check all :+1:

**Pull request merged**
