### PR TITLE
Start overhaul of typehints and TS type definition

### PR DESCRIPTION
**Pull request by allejo**
I'm in the process of slowly looking through the codebase and fixing some JSDocs to better generate a TypeScript definitions file.

This is still a WIP, but is this something the project maintainers would be interested in? Currently, working with the generated AST in TS is pretty near impossible for me with the current typing files.

### CODE REVIEW

**Comment by ichiriac** [comment]
Hi @allejo, I'm really interested on that :+1:  ! The project leaks types definition for typescript, i've started something but it's nearly impossible to maintain with all nodes. 

I'm glad that you started something. Let me know when you get something to test

**Comment by allejo** [comment]
Hey @ichiriac! I had to step away from this PR for a bit, but yea I'll be picking this up again soon and I'll let you know when it's ready to test.

When you said the project leaks type definitions, did you mean the current types or this PR?

**Comment by allejo** [comment]
yo @ichiriac, so I think I've completed as much work I can do in this PR and gotten a reasonably verbose type definition being generated

**Comment by ichiriac** [comment]
Hi @allejo, thanks for your work. I plan to work on the project in few days and I'll release it with your changes. 

I wish you the best,
Best regards,
Ioan

**Comment by allejo** [comment]
as an FYI, I've added 05fcedda111f8d5b39b3d496ec58132467b394a0 to export `Engine` yet another way. I can't figure out how to export it by default via JSDoc, so to get the .d.ts file accurate, I added this extra export method...

**Comment by ichiriac** [comment]
Hi @allejo sorry for the late, many thanks for your contribution. It will be released in 3.0.3

**Pull request merged**
